### ISSUE TITLE
match函数中的mark变量是干嘛用的?

### ISSUE THREAD

**Issue by LiZeC123** [gansidui/ahocorasick#4]
Match函数中有一个mark变量用来标记是否加入到最终的结果之中. 对于具体的关键词表, 这个map对性能有非常大的影响, 不知道设置这个变量的意图是什么?

**Comment by gansidui** [comment]
标记是否匹配过，这里为了让Match支持并发，mark只能为局部变量

**Comment by LiZeC123** [comment]
作者你好, 我之前的表达可能不够清楚. 

我其实想问的是为什么需要有一个变量来标记是否匹配过?  这是不是意味着 如果不进行标记 在某些特殊的词表下会导致 类似 死循环 的逻辑错误?  如果我删除这个变量并剔除相关的逻辑是否会导致逻辑错误? 按照我了解到的ac算法, 并没有涉及是否需要标记已经匹配过的问题, 所以对这个地方有疑问. 

另外根据我的测试, 这个map相关的操作的耗时在整个函数中占据了相当大的比例, 如果能删除这个map, 性能能够有好几倍的提升.  我有一个场景想使用这个项目, 但是项目对于耗时比较敏感, 所以想确认一下这个变量能不能优化掉.

最后, 还是感谢您抽空回答我的问题, 祝您新年快乐.

**Comment by gansidui** [comment]
防止重复匹配，看你的业务需求，去掉也是没问题的，比如下面这个代码
```
	ac := NewMatcher()

	dictionary := []string{"she", "he", "say", "shr", "her"}
	ac.Build(dictionary)

	ret := ac.Match("yasheherhs")

	for _, term := range ret {
		fmt.Printf("%d %s\n", term.EndPosition-len(dictionary[term.Index])+1, dictionary[term.Index])
	}
```

按现在的代码逻辑，输出结果为：
```
2 she
3 he
5 her
```

如果去掉了mark，输出结果为：
```
2 she
3 he
5 he
5 her
```
其中`he`匹配了两次，如果你业务本身不需要，是可以去掉mark的。

**Comment by LiZeC123** [comment]
我的业务场景就是需要匹配所有出现的地方, 所以也是要去掉mark的. 非常感谢~
